name: Flutter

on:
  pull_request:
    branches: '*'
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Report coverage
        run: bash <(curl -s https://codecov.io/bash)
